// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCax7QgkzKQYsgl2pEuTLYoh-fP-iXvKgs',
    appId: '1:628204193428:web:2a2533cbec3eb644565681',
    messagingSenderId: '628204193428',
    projectId: 'mapjok-dbaca',
    authDomain: 'mapjok-dbaca.firebaseapp.com',
    storageBucket: 'mapjok-dbaca.firebasestorage.app',
    measurementId: 'G-LE93MHFCJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASUbmeQ4BVaQ7OkE54aK7pFTTMw1FT_eU',
    appId: '1:628204193428:android:68858a1a62b9d47c565681',
    messagingSenderId: '628204193428',
    projectId: 'mapjok-dbaca',
    storageBucket: 'mapjok-dbaca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBchDHDI-bELamYMZxaH0jp9TevvubLpk8',
    appId: '1:628204193428:ios:7addac22bf0d0942565681',
    messagingSenderId: '628204193428',
    projectId: 'mapjok-dbaca',
    storageBucket: 'mapjok-dbaca.firebasestorage.app',
    iosBundleId: 'com.example.banglaMapjok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBchDHDI-bELamYMZxaH0jp9TevvubLpk8',
    appId: '1:628204193428:ios:7addac22bf0d0942565681',
    messagingSenderId: '628204193428',
    projectId: 'mapjok-dbaca',
    storageBucket: 'mapjok-dbaca.firebasestorage.app',
    iosBundleId: 'com.example.banglaMapjok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCax7QgkzKQYsgl2pEuTLYoh-fP-iXvKgs',
    appId: '1:628204193428:web:dd7fc81445d22351565681',
    messagingSenderId: '628204193428',
    projectId: 'mapjok-dbaca',
    authDomain: 'mapjok-dbaca.firebaseapp.com',
    storageBucket: 'mapjok-dbaca.firebasestorage.app',
    measurementId: 'G-J430YTCF0K',
  );
}
